Repository melkati/CO2-Gadget, pull requests merged in 2024-01, with the labels that each got.

#98 Add ESPNOW icon
  CO2_Gadget_TFT.h
  icons.h
  platformio.ini
Labels: enhancement

#106 Fix serial communication when changing CPU frequency
  CO2_Gadget.ino
Labels: bug

#108 Update Sensirion Gadget BLE library and refactor code
  CO2_Gadget_BLE.h
  CO2_Gadget_Menu.h
  CO2_Gadget_TFT.h
  platformio.ini
Labels: enhancement

#93 Fix esp32dev environent
  CO2_Gadget.ino
  CO2_Gadget_Buttons.h
  CO2_Gadget_Menu.h
Labels: enhancement

#122 Development
  CO2_Gadget.ino
  CO2_Gadget_Buttons.h
  CO2_Gadget_Menu.h
  CO2_Gadget_OLED.h
  CO2_Gadget_Preferences.h
  CO2_Gadget_TFT.h
  README.md
  platformio.ini
Labels: bug, enhancement
